// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: breadcrumb
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "breadcrumb-link": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "breadcrumb-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "breadcrumb-chevron": "light-dark(rgb(201 204 207), rgb(73 76 80))"
      },
      "spacing": {
        "breadcrumb-gap": "4px",
        "breadcrumb-padding-x": "16px"
      }
    },
  },
};
