// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: item
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "item-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "item-hover": "light-dark(rgb(226 235 245), rgb(3 43 99))",
        "item-active": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "textColor": {
        "item-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "item-active": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "item-divider": "light-dark(rgb(255 255 255 / 0.102), rgb(0 0 0 / 0.102))"
      },
      "fill": {
        "item": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "item-gap-x": "8px",
        "item-gap-y": "4px",
        "item-height-min": "40px",
        "item-nesting-padding-l1": "0px",
        "item-nesting-padding-l2": "24px",
        "item-nesting-padding-l3": "48px",
        "item-nesting-padding-l4": "72px",
        "item-nesting-padding-l5": "96px",
        "item-padding-x": "8px",
        "item-padding-x-small": "4px",
        "item-padding-y": "8px",
        "item-width-min": "128px"
      }
    },
  },
};
