// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: menu-item
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "menu-item-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "menu-item-hover": "light-dark(rgb(226 235 245), rgb(3 43 99))",
        "menu-item-active": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "textColor": {
        "menu-item-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-active": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "menu-item-divider": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "fill": {
        "menu-item": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "menu-item-gap": "8px",
        "menu-item-height-header": "64px",
        "menu-item-padding-l2": "40px",
        "menu-item-padding-x": "16px",
        "menu-item-padding-y": "8px",
        "menu-item-width": "256px",
        "menu-item-width-collapsed": "48px"
      }
    },
  },
};
