// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: switch
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "switch-active": "light-dark(rgb(70 185 89), rgb(36 143 54))",
        "switch-disabled": "light-dark(rgb(248 250 252), rgb(0 21 51))",
        "switch-inactive": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "switch-circle-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "switch-circle-off": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "switch-circle-on": "light-dark(rgb(255 255 255), rgb(0 0 0))"
      },
      "borderColor": {
        "switch-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "spacing": {
        "switch-units-border": "1px",
        "switch-units-circle": "12px",
        "switch-units-gap": "8px",
        "switch-units-height": "16px",
        "switch-units-padding-x": "2px",
        "switch-units-padding-y": "2px",
        "switch-units-width": "32px"
      },
      "borderRadius": {
        "switch-units-radius": "999px"
      }
    },
  },
};
