// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: tooltip
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "tooltip": "light-dark(rgb(25 27 35 / 0.898), rgb(25 27 35 / 0.898))"
      },
      "textColor": {
        "tooltip": "light-dark(rgb(255 255 255), rgb(0 0 0))"
      },
      "spacing": {
        "tooltip-global-padding-x": "12px",
        "tooltip-global-padding-y": "8px",
        "tooltip-global-width-max": "256px",
        "tooltip-global-width-min": "48px"
      },
      "borderRadius": {
        "tooltip-global-radius": "4px"
      }
    },
  },
};
