// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: chip
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "spacing": {
        "chip-global-height": "24px",
        "chip-global-height-lg": "32px",
        "chip-global-padding-x": "8px",
        "chip-global-width-max": "512px"
      }
    },
  },
};
