// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: icon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "spacing": {
        "icon-16-size": "16px",
        "icon-16-stroke": "1.6px",
        "icon-24-size": "24px",
        "icon-24-stroke": "2px",
        "icon-32-size": "32px",
        "icon-32-stroke": "2.5px"
      }
    },
  },
};
