// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: menu-item
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "menu-item-idle": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "menu-item-hover": "light-dark(rgb(226 245 244), rgb(3 58 54))",
        "menu-item-active": "light-dark(rgb(209 240 237), rgb(4 73 67))"
      },
      "textColor": {
        "menu-item-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-active": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "menu-item-divider": "light-dark(rgb(209 240 237), rgb(4 73 67))"
      },
      "fill": {
        "menu-item": "light-dark(rgb(51 153 145), rgb(51 153 145))"
      },
      "spacing": {
        "menu-item-gap": "8px",
        "menu-item-height-header": "64px",
        "menu-item-padding-l2": "40px",
        "menu-item-padding-x": "16px",
        "menu-item-padding-y": "8px",
        "menu-item-width": "256px",
        "menu-item-width-collapsed": "48px"
      }
    },
  },
};
