// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: tag
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "spacing": {
        "tag-global-height": "24px",
        "tag-global-height-sm": "20px",
        "tag-global-padding-x": "8px",
        "tag-global-padding-x-sm": "4px",
        "tag-global-width-max": "256px"
      }
    },
  },
};
