// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: Chips
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "chips-container-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "chips-container-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "chips-container-idle": "light-dark(rgb(244 245 245), rgb(24 25 27))"
      },
      "textColor": {
        "chips-label": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "chips-border-active": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "chips-border-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "chips-border-idle": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fill": {
        "chips-icon": "light-dark(rgb(73 76 80), rgb(201 204 207))"
      },
      "fontFamily": {
        "chips-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "chips-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "chips-border-width": "1px",
        "chips-container-gap": "4px",
        "chips-container-height": "24px",
        "chips-container-padding-x": "8px",
        "chips-container-width-min": "48px",
        "chips-icon-size": "16px"
      },
      "borderRadius": {
        "chips-border-radius": "12px"
      }
    },
  },
};
